name: Keep Streamlit App Alive

on:
  schedule:
    # Runs every 4 minutes to prevent free-tier app from sleeping
    - cron: '*/4 * * * *'
  workflow_dispatch: # Allow running this workflow manually from the Actions tab

jobs:
  visit-sites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Playwright and dependencies
        run: |
          pip install playwright==1.54.0
          python -m playwright install --with-deps chromium

      - name: Visit the Streamlit app
        env:
          APP_URL: "https://price-tracker-app-5joo.onrender.com/?endpoint=latestPrice"
        run: python scripts/visit_page.py
